FROM node:10.15.3

WORKDIR /usr/src/app

COPY koa/ /usr/src/app

RUN npm install

RUN git clone https://github.com/vishnubob/wait-for-it.git

RUN apt-get update && apt-get install -y build-essential && apt-get install -y python

EXPOSE 3000

CMD ["npm","run", "dev"]

